global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'lowkey'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          instance: 'lowkey-node-1'
    metrics_path: '/metrics'
